import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Hero from "./components/Hero";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-cover h-screen" style={{backgroundImage: "url('/venom-3bg.jpg')"}}>
      <Navbar />
      <Hero />
        {children}
      </body>
    </html>
  );
}
